name: Nightly checks

on:
  # workflow_dispatch so that it can be triggered manually if needed
  workflow_dispatch:
  schedule:
    - cron: "34 23 * * *"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [ main, 1.1.x ]
    name: E2E Tests - ${{ matrix.branch }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.branch }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4 # default branch will be checked out by default on scheduled workflows
        with:
          fetch-depth: 0

      - if: ${{ matrix.branch != 'main' }}
        name: Checkout ${{ matrix.branch }} branch
        run: git switch ${{ matrix.branch }}

      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version-file: 'go.mod'

      - name: Start Minikube
        uses: medyagh/setup-minikube@606b71970c783154fe49b711486c717f5780f485 # v0.0.15
        with:
          addons: ingress

      - name: Run E2E tests
        env:
          BACKSTAGE_OPERATOR_TESTS_PLATFORM: minikube
        run: |
          latestNext="next"
          # for main branch, use next tags; for 1.x branches, use :latest tags
          if [[ "${{ matrix.branch }}" != "main" ]]; then
            latestNext="latest" 
          fi
          export IMG="quay.io/janus-idp/operator:${latestNext}"
          echo "--> Testing Operator Image: ${IMG} <--"
          make test-e2e
